import { Inter } from 'next/font/google'
import './globals.css'
import toast, { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <main className='mx-auto max-w-screen-lg h-screen'>
        {children}
        </main>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 10000,
          }}
        />
        </body>
    </html>
  )
}
